### ISSUE TITLE
App closing

### ISSUE THREAD

**Issue by fabianski7** [CTemplar/android#189]
**Describe the bug**
The app is closing when trying to enter the settings.

**To Reproduce**
1. Open the side menu
2. Click on Settings
3. The app closes

**Logs**
https://bin.privacytools.io/?bd9458765ad8a2b3#TGUK77YmOMpuYY/WJINggMhNehWAP64fzT2jKTul3Q0=

**Smartphone (please complete the following information):**
 - Device: Oneplus 6 (A6000)
 - OS: Android 10 (kernel 4.9.219)
 - Version: 1.2.6 (F-DROID)

**Additional context**
I'm not using GAPPS

**Comment by fabianski7** [comment]
I had reported this error a few days ago by e-mail.

**Comment by alexdwork2018** [comment]
It already fixed in dev and will appear in the new prod release. Thank you!
