### ISSUE TITLE
Application navigation issues

### ISSUE THREAD

**Issue by fabianski7** [CTemplar/android#207]
**Describe the bug**
I'm experiencing some issues regarding the application's behavior in your navigation. Some examples:

If you are in the contact list, or in some folder, such as draft, sent, unread, etc., and click the android back button, the application is **closed**. The correct would be **back** to the inbox not? 

This issue with the back button also occurs within the application settings.If you are in some configuration, such as notification, and click the go back button, the application **backs to the inbox**, **not to the previous configuration**. 
The **right** behavior happens in the Filters settings, if you click back, the user is redirected to the previous configuration, not to the inbox.

In addition to these fixes, I believe a confirmation box should be added alerting the user whenever the application is about to close. This would avoid some of these unexpected behaviors. 

**Smartphone (please complete the following information):**
 - Device: Oneplus 6 (A6000)
 - OS: Android 10 (kernel 4.9.223)
 - Version 1.2.7 (F-DROID)

**Additional context**
I'm not using GAPPS;
Using the back button of the application itself, on the top left, does not solve this problem.

**Comment by The-Hidden-Hand** [comment]
We're looking into it and release a fix asap. Thanks for reporting!

**Comment by alexdwork2018** [comment]
@fabianski7 Thank you for describing the issues! The update was sent for publication and has already been released by the Google Play, after a while the F-Droid will also release version 1.2.8, please update the application when it becomes available
