### ISSUE TITLE
"Enter Valid Email Address", when email contains "="

### ISSUE THREAD

**Issue by Lissy93** [CTemplar/android#240]
<img src="https://i.ibb.co/8836b4t/CTemplar-Screenshot-Invalid-email-error.png" alt="Screenshot of CTemplar Android App, showing Invalid Email Error Message" width="380" align="right"/>

**Describe the bug**
When sending a message, or adding a contact where the email contains an `=` in the first part, an error message is displayed saying `"Enter Valid Email Address"`.

It is valid to include such a character in an email address, and this is commonly used in mail forwarding services, such as [AnonAddy - to send a message from an alias](https://anonaddy.com/help/sending-email-from-an-alias/). It is frustrating to not be able to proceed in sending such an email at all.

**To Reproduce**
1. Open app, and tap the 'Compose' icon in bottom right
2. Enter email address, which contains an `=` in the first part
3. Complete all other fields (from, subject, body etc)
4. Tap the 'Send' icon on top right
5. See error popup, reading `Enter Valid Email Address`

**Expected behavior**
Email should send, with no problems.

**Screenshots**
See, right -->

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4
 - OS: Android 10
 - Version: 22

**Additional context**
 Note that this also applies to create a contact, and everywhere else where an email address is validated.

**Comment by Lissy93** [comment]
I believe it is caused by by the regex pattern, `EMAIL_LIST` defined in [`EditTextUtils.java`](https://github.com/CTemplar/android/blob/master/app/src/main/java/mobileapp/ctemplar/com/ctemplarapp/utils/EditTextUtils.java#L22)\#22 (and called in `onClickSend()` in [`SendMessageFragment.java`](https://github.com/CTemplar/android/blob/master/app/src/main/java/mobileapp/ctemplar/com/ctemplarapp/message/SendMessageFragment.java#L495)\#495, among other places).

Just adding the offending `=` char, within the `[a-zA-Z0-9+._%\-+]` block should fix it. However, there are still use cases where is not ideal, using a proven regex (such as [this one](http://emailregex.com/)), may be a better option?

**Comment by The-Hidden-Hand** [comment]
Thanks for your contribution @Lissy93 

We'll review your solution and release it as soon as @alexdwork2018 is back from his off-days.

**Comment by alexdwork2018** [comment]
@Lissy93 App used an Android-provided regex pattern, which seems to be outdated. For better reliability, I have updated regex to recommended by RFC 5322. Thank you for the detailed description of other bugs, fixes will be released soon!
