### ISSUE TITLE
App closing when trying to write a mail

### ISSUE THREAD

**Issue by boistordu** [CTemplar/android#277]
**Describe the bug**
App crashing when I click on the pen to write a mail. 

**To Reproduce**
Same

**Expected behavior**
...

**Smartphone (please complete the following information):**
 - Device: fairphone3 
 - OS: Android 10
 - Version 1.4

**Comment by D4RKPHOENIX** [comment]
I just tested this on Graphene OS/Android 11 on a Pixel 3XL.  I was able to successfully compose and send an email.

**Comment by boistordu** [comment]
Yes well it's under Android 11 so I don't know. I ve rebooted the phone. I ve uninstalled and reinstalled the app and the bug is persistent so...

**Comment by D4RKPHOENIX** [comment]
Yes, I understand your predicament.  I was just trying to give the dev more info to help narrow down the problem.

**Comment by boistordu** [comment]
Maybe a specific customization from fairphone in the Android ecosystem itself ?

**Comment by alexdwork2018** [comment]
@boistordu Thank you for the reporting, the fix will be released soon!

**Comment by alexdwork2018** [comment]
@boistordu Thank you for the reporting. Fix will be released soon!

**Comment by alexdwork2018** [comment]
The bug has been fixed in v1.4.1. Please update the app when an update becomes available to you
