### ISSUE TITLE
Email Body Not Displaying Properly

### ISSUE THREAD

**Issue by D4RKPHOENIX** [CTemplar/android#278]
**Describe the bug**
When opening an email the body is displayed in HTML text instead of the appropriate format.

**To Reproduce**
1. Go to any email in the app.
2. Click on an email to open it
3. See HTML text.

**Expected behavior**
The email should open with properly formatted text, background, and images viewable as they are on the web version of Ctemplar.

**Screenshots**
![Email Body in App](https://user-images.githubusercontent.com/8397382/99197624-464dab80-2759-11eb-8fb6-d7e376e142d0.png)
![Same Email Body as Above Viewed on the Ctemplar Website](https://user-images.githubusercontent.com/8397382/99197632-54033100-2759-11eb-8f22-09cdb0a7bdfd.png)

**Smartphone (please complete the following information):**
 - Device: [Google Pixel 3XL]
 - OS: [Graphene OS/Android]
 - Version [11]

**Additional context**
Emails that are sent in plain text are viewable on the app.  The app version 1.4.0 was downloaded and installed via the F-droid app.

**Comment by alexdwork2018** [comment]
@D4RKPHOENIX Thank you for the reporting. We are already working on a fix and will release it soon!

**Comment by alexdwork2018** [comment]
The bug has been fixed in v1.4.1. Please update the app when an update becomes available to you

**Comment by D4RKPHOENIX** [comment]
Thank you for the quick fix!  Any idea how long it takes for the update to get pushed to F-droid?
