### ISSUE TITLE
Dark mode setting not saving

### ISSUE THREAD

**Issue by SecretestSquirrel** [CTemplar/android#284]
**Description**
Dark mode setting is not saving when set to "off". Upon next entry to app it reverts back to default "Auto" selection.

**Steps to reproduce the behavior**
1. Go to 'Settings-->Dark Mode'
2. Click 'Off'
3. Log out, log back in
4. See setting reverted to 'Auto(Detect)' default

**Expected behavior**
Setting to be saved

**Smartphone**
 - Device: Samsung S8+ and Pixel 3a
 - OS: Android 9 and GrapheneOS Android 11
 - Version 1.4.0

**Comment by D4RKPHOENIX** [comment]
I can reproduce this with my Pixel 3 XL using Graphene OS 11.  The dark mode setting remains off if you exit the app without logging out. If you log out and log back in the setting reverts to auto.

**Comment by alexdwork2018** [comment]
Hello @SecretestSquirrel,

Thanks for reporting. We have work on this issue and notify you when the fix will be released.

Kind regards.

**Comment by alexdwork2018** [comment]
@SecretestSquirrel Now DarkMode setting will be saved in your account settings and repaired when you re-login. This feature will be available in the next release.

Additional info: Now if you have turned off the dark theme on the Web Client, the theme setting in the app will only change if it was dark before. If the dark theme in the app was in an "off" or "auto" state then this value will remain. Thus you can turn off the dark theme on the Web Client but remain it in the app if by Android system defaults dark mode is enabled. Or you can forcibly disable the dark theme in the app settings if you want to remain dark theme only in the Android system.
