### ISSUE TITLE
Body cut short and not displaying hyperlink

### ISSUE THREAD

**Issue by SecretestSquirrel** [CTemplar/android#285]
**Description**
Received encrypted email from Tutanota supposed to contain hyperlink for outside decryption. Email body stopped several lines short of actual message displayed in webclient, also no hyperlink was present.

**Screenshots**
Full message 
![IMG_20201122_074621_714](https://user-images.githubusercontent.com/74485231/99898552-0f682000-2c9a-11eb-87e3-dec8521e90ab.jpg)
Message as shown in app missing lines and hyperlink 
![IMG_20201122_082343_807](https://user-images.githubusercontent.com/74485231/99898784-0ed08900-2c9c-11eb-9a54-d7a752facde3.jpg)

**Smartphone**
 - Device: Samsung S8+ and Pixel 3a
 - OS: Android 9 and GrapheneOS
 - Version: A9(Kernel 4.4.153) and A11(Kernel 4.9.223)

**Additional context**
I know I'm probably killing you all, but it's all only with intentions to help improve ¯\_(ツ)_/¯

**Comment by alexdwork2018** [comment]
@SecretestSquirrel Thank you for the report! Body cut short - should be fixed after update to v1.4.2
