### ISSUE TITLE
Email Body is Blank

### ISSUE THREAD

**Issue by D4RKPHOENIX** [CTemplar/android#286]
**Describe the bug**
The email Body is completely blank. No text or pictures are shown at all. 

**To Reproduce**
1. Go to inbox and open any email. 

**Expected behavior**
Open email and view it's contents. 

**Screenshots**
Email viewed in the app. 
![Screenshot_20201123-083831](https://user-images.githubusercontent.com/8397382/99975484-e910b600-2d67-11eb-9f93-cc842c02230e.png)

Same email viewed on the Ctemplar website.
![Screenshot_20201123-083946](https://user-images.githubusercontent.com/8397382/99975558-02196700-2d68-11eb-9fcb-af03356c2061.png)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3 XL
 - OS: Graphene OS Android
 - Version 11

**Additional context**
Using Ctemplar 1.4.1 installed from the F-droid app store. I cleared the data and cache for the app and after logging back in I still had the problem.

**Comment by alexdwork2018** [comment]
Thank you for the report! Display of html content is fixed and will available in v1.4.2
