### ISSUE TITLE
Compacting upper section while writing email

### ISSUE THREAD

**Issue by mezysinc** [CTemplar/android#297]
**Describe the bug**
Half of screen is taken by keyboard and the upper section cannot be rolled up which leave you only with one line of space visible.

**To Reproduce**
1. Go to 'compose email'
2. Switch to 'section for writing email content'
3. What's happening? 'there is only one line visible in composing section'
4. See display layout on screenshot attached

**Expected behavior**
Be able to compact upper area of email while writing email content.

**Screenshots**
Added screenshot to help explain the problem.

![ct em](https://user-images.githubusercontent.com/74458162/102690633-7a4b3f00-41e5-11eb-97b2-70547d13e088.png)

Thanks

**Comment by alexdwork2018** [comment]
@mezysinc The bug has been fixed and will be available in the next release. Now via scroll, you can use more area for writing the letter. Thanks for your reporting!
