### ISSUE TITLE
f-droid update

### ISSUE THREAD

**Issue by bingoxo** [CTemplar/android#300]
playstore version : 1.4.3

f-droid : 1.4.2

can you keep it as to date please ?

**Comment by bingoxo** [comment]
@licaon-kter sorry for the ping , but can you tell us why isn't the latest version building ?

**Comment by licaon-kter** [comment]
There's no new version: https://github.com/CTemplar/android/releases right?

**Comment by alexdwork2018** [comment]
The Play Store version received an update to fix the work with notifications. The F-Droid version does not use Firebase, so it does not need this update. Version matching will be reverted on next update
