### ISSUE TITLE
Proxy settings and Tor onion support

### ISSUE THREAD

**Issue by BayLee4** [CTemplar/android#301]
**Is your feature request related to a problem? Please describe.**

Additional privacy and security, could also be used in case of censorship. Currently one could not use its own proxy to access the service.

**Describe the solution you'd like**

Adding a proxy settings (Socks, HTTP), and add option to use the Tor onion service v3 (which is already in production), instead of clearnet URL defined here : https://github.com/CTemplar/android/blob/master/app/build.gradle#L49
Could also be configured to start Orbot when this settings is set, the same way F-droid is currently doing it : https://github.com/f-droid/fdroidclient/blob/master/app/src/main/java/org/fdroid/fdroid/FDroidApp.java#L663

**Describe alternatives you've considered**

Currently, the alternative is using the [onion web application](http://mail.ctemplarpizuduxk3fkwrieizstx33kg5chlvrh37nz73pv5smsvl6ad.onion), but it would be more secure and convenient to use it directly in the android application. 
One could also use Tor/VPN system-wide, but it's also not convenient (would take the only available VPN slot on android), and would still not benefits the additional security/privacy of the onion service.

**Additional context**

Screenshot from F-droid : 

<img src="https://user-images.githubusercontent.com/63376748/104132854-3250af80-5380-11eb-8e59-d281a0be71b9.png" height="50%" width="50%">

**Comment by BayLee4** [comment]
Any update on this ?

**Comment by The-Hidden-Hand** [comment]
@alexdwork2018 
Could we give some priority to this?

**Comment by BayLee4** [comment]
I guess that means no 😕

**Comment by BayLee4** [comment]
@alexdwork2018 @The-Hidden-Hand With all the recent events about Protonmail giving IP addresses of its users to authorities, this feature could really be an important factor for considering CTemplar over Protonmail.

Could we expect some progress on this any soon ?

**Comment by The-Hidden-Hand** [comment]
@BayLee4 
This is on testing phase and it will be included in the next release.

**Comment by The-Hidden-Hand** [comment]
@nivritgupta 
Do you think this would be possible on iOS?

**Comment by BayLee4** [comment]
@The-Hidden-Hand That's awesome, congratulation to the team !

I looked at the Pull Request and it seems that even when using Tor, the application still use the clearnet URL instead of the onion URL. Could it be made to connect to the onion URL for more privacy (and security) ? It would make the connection to stay within the Tor network, thus eliminating the risk of malicious exit nodes, and as you already have one up and running it would be a shame not to use it !

**Comment by alexdwork2018** [comment]
Hi @BayLee4 . The new version already sent for publication and will soon be available in stores. It will also get improvements in the near future, so please stay tuned.

**Comment by The-Hidden-Hand** [comment]
Thanks for the work @alexdwork2018 
Let us know any other suggestion @BayLee4 !

**Comment by The-Hidden-Hand** [comment]
@BayLee4 
I think the issue has been solved.
Please let us know any other suggestion!

**Comment by reg3xp** [comment]
SOCKS5 support would be great.
User can use SOCKS5 proxy for connecting to Tor.

**Comment by BayLee4** [comment]
Hi @The-Hidden-Hand, nothing changed since my last comment ('Use Tor' button still not working, and onion URL still not used). I've waited to see if there was an upcoming update about it but there isn't, could you please reopen the issue until these problems are resolved ? Thanks.

**Comment by alexdwork2018** [comment]
Hi @BayLee4 ! I managed to repeat your issue on the device without Google Play. If you use an official source to install the CTemplar app, such as Google Play or F-Droid Store, then activating 'Use Tor' will try to install Orbot from these stores.
But here is a problem with the F-Droid Store. Now it does not display Orbot without additional settings. You need to open the F-Droid Store app -> 'Settings' -> 'Repositories' and enable 'Guardian Project Official Releases'. After that, you can enable 'Use Tor' in the CTemplar app and it will propose to install Orbot from the F-Droid store. If the Orbot is already installed, CTemplar will send a command to start service to the Orbot app. Later we will add hints for this case.

If you don't have any of the supported stores and enable 'Use Tor' options it will open the web browser as you described. F-Droid web page does not show you the Orbot app instead you will see only 404 pages. But even in this case, there is a way out. You can install Orbot yourself and if the package name of the app matches the original one, then everything will work. Be careful on installing apps from unsafe sources. If this 'Use Tor' option doesn't work for you, you can stat Orbot manually and instead 'Use Tor' activate the 'HTTP Proxy' option. In the address field, enter 127.0.0.1 and in the port field 8118 (Orbot app address). As result, all CTemplar traffic must go through the Orbot app.

**Comment by BayLee4** [comment]
Hi @alexdwork2018, I already have Tor installed from the Guardian Project repository in f-droid (and just as shown in my first [comment](https://github.com/CTemplar/android/issues/301#issue-782886994), I'm using it with F-droid without any issue).

Still, the CTemplar application seems not to communicate with Orbot even if installed this way, in contrast to the F-droid application which start and use it normally.

**Comment by alexdwork2018** [comment]
@BayLee4 Above you wrote that the activation of the 'Use Tor' gives you a choice between the Browser and the F-Droid store app. When you select F-Droid, does it display Orbot installed on your device? CTemplar uses the same library and code to check whether Orbot is installed as the F-Droid Store app. Even if CTemplar app for any reason cannot detect the installed Orbot on your device, click on 'Use Tor' should activate setting switch and work with original Orbot app.
Can you please specify the version of the device operating system you are using? This would help in repeating your issue case.

Please note that by default Orbot should work on HTTP 8118 port and CTemplar expect these parameters. You can check and correct this in the Orbot app.

**Comment by BayLee4** [comment]
> @BayLee4 Above you wrote that the activation of the 'Use Tor' gives you a choice between the Browser and the F-Droid store app. When you select F-Droid, does it display Orbot installed on your device?

Yes it does.
> Can you please specify the version of the device operating system you are using? This would help in repeating your issue case.

I'm on Android 12, running without Play Services. I was previously on Android 11 and if I recall correctly the issue was already present at that time.

> Please note that by default Orbot should work on HTTP 8118 port and CTemplar expect these parameters. You can check and correct this in the Orbot app.

Yes this is correct, and I confirm that when ignoring/closing the F-droid/web page which opens automatically when clicking on the 'Use Tor' button, and then manually starting Orbot, the CTemplar application does use the proxy correctly and is able to function as normal. 
It looks like the issue is only related to the 'Detect if Orbot is installed / Start it' part of the integration.

@alexdwork2018 Please tell me if you need additional informations, I will provide them, thanks.

**Comment by alexdwork2018** [comment]
@BayLee4 Thank you for the details. The problem with opening Orbot instead of launching onion service. It appear from the inability to determine if Orbot is installed on your device. With the transition to support for the latest SDK, the Android operating system filters information about installed apps. Therefore, CTemplar cannot determine if Orbot is installed on the device on your device. At the same time, the operating system can return a real list of installed on device apps for apps for which this is the main function, such as apps stores.

You can read more here - https://developer.android.com/training/package-visibility

**Comment by alexdwork2018** [comment]
@reg3xp @BayLee4 SOCKS proxy and Tor onion address support will appear in the one of the next updates. Keep for updates.

**Comment by alexdwork2018** [comment]
@reg3xp @BayLee4 SOCKS proxy and Tor onion address support will appear in one of the next updates. Stay tuned.

**Comment by BayLee4** [comment]
> @BayLee4 Thank you for the details. The problem with opening Orbot instead of launching onion service. It appear from the inability to determine if Orbot is installed on your device. With the transition to support for the latest SDK, the Android operating system filters information about installed apps. Therefore, CTemplar cannot determine if Orbot is installed on the device on your device. At the same time, the operating system can return a real list of installed on device apps for apps for which this is the main function, such as apps stores.
> 
> You can read more here - https://developer.android.com/training/package-visibility

That makes a lot of sense, if I understand correctly the CTemplar application would need to [declare](https://developer.android.com/training/package-visibility/declaring) the Orbot package name to resolve this visibility issue ? If you need me to test a build using it don't hesitate to ping me.

> @reg3xp @BayLee4 SOCKS proxy and Tor onion address support will appear in one of the next updates. Stay tuned.

Great news ! Thanks a lot for your work @alexdwork2018

**Comment by BayLee4** [comment]
Just updated to the latest version and I confirm that everything works flawlessly !
@alexdwork2018 @The-Hidden-Hand You guys are the best 👏

**Comment by reg3xp** [comment]
> @reg3xp @BayLee4 SOCKS proxy and Tor onion address support will appear in one of the next updates. Stay tuned.

Thanks for the update
Your proxy settings style is similar to F-Droid
AFAIK the use TOR option in F-Droid connects to orbot via SOCKS5 port 9050
Obviously it wouldn't work if you change the SOCKS or HTTP port in orbot.
Now that CTemplar has SOCKS support I don't see any reason to keep the use TOR option.

**Comment by BayLee4** [comment]
> AFAIK the use TOR option in F-Droid connects to orbot via SOCKS5 port 9050 

No, it uses HTTP port 8118.

> Obviously it wouldn't work if you change the SOCKS or HTTP port in orbot. Now that CTemplar has SOCKS support I don't see any reason to keep the use TOR option.

The 'Use Tor' button must stay : how would the CTemplar application know if the onion URL should be used then ? How would it know if it should start the Orbot application ? Using a SOCKS/HTTP proxy doesn't necesseraly imply using Tor/Orbot.

It may be interesting to be able to use 'Custom Proxy' in conjunction with the 'Use Tor' button, in case anyone disabled the default 8118 port, but honestly I don't see any reason why would anyone do this. Even F-droid doesn't permit that, and CTemplar now behave 100% like F-droid which is good.

**Comment by reg3xp** [comment]
> The 'Use Tor' button must stay : how would the CTemplar application know if the onion URL should be used then ? How would it know if it should start the Orbot application ? Using a SOCKS/HTTP proxy doesn't necesseraly imply using Tor/Orbot.

Some websites redirect the user upon detecting a Tor exit ip address to the onion domain.
I don't know if that would be possible for you.

App doesn't have to start the orbot when you're using a different port (you have already started it).

Use Tor option is more user-friendly, gotta give that to you.

**Comment by BayLee4** [comment]
> Some websites redirect the user upon detecting a Tor exit ip address to the onion domain. I don't know if that would be possible for CTemplar.

That's not how it work, those website add a special `Onion-Location` header which the Tor Browser reads and redirect accordingly. Tor/Orbot alone has no way to do that.
> 
> App doesn't have to start the orbot when you're using a different port (you have already started it).

So what are you proposing is : 

1) Default port / Default proxy type => CTemplar app starts the Orbot app and use the .onion URL
2) Non default port / Non default proxy type => CTemplar app does not start the Orbot app (and thus does not use the .onion URL because of the reason stated above)

Isn't it the exact same behaviour that it currently have?
