### ISSUE TITLE
Ctemplar keeps logging me out for no reason 

### ISSUE THREAD

**Issue by Pentaphon** [CTemplar/android#305]
### Your environment

Ctemplar 1.4.3 Google Play version on a Moto G7 running Android 9 stock.

### Steps to reproduce

There's no real steps. I just sign in after checking the box to keep me logged in and maybe after the 2nd or 3rd time I log in after that, I'm logged out. This is not abnormal usage. Just normal everyday usage, opening the app every few days to use it. It just keeps logging me out for no reason. 

### Expected behavior

It should not log me out unless I log myself out of the app. 

### Actual behavior

I open the app to use it and it just shows me the log in screen even though I never logged myself out.

**Comment by alexdwork2018** [comment]
@Pentaphon The fix is ready and will be available in the next version. Thanks for your reporting!
