### ISSUE TITLE
App crashes when trying to exit while it's loading

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/android#306]
I have also experienced a similar issue on the Android mobile app on occasion, fyi. Generally occurs when in another tab, say "Sent" emails, then press back button which takes you to "Inbox", which shows as loading. If I hit the back button again while loading in an attempt to exit, I sometimes get an app crash.

Can open an issue in Android repo if you'd like.

_Originally posted by @SecretestSquirrel in https://github.com/CTemplar/webclient/issues/898#issuecomment-757512105_

**Comment by alexdwork2018** [comment]
@The-Hidden-Hand I was unable to reproduce the issue. Perhaps there is more info about the user device or a video demo of this error. I also think we can see this error in bug reports if the user has activated this function in the app settings.
