### ISSUE TITLE
Allow to select all the messages in a folder

### ISSUE THREAD

**Issue by tuekacode** [CTemplar/android#331]
Enables the user to :
- select many messages and have the options to [ Delete All / Mark All As Read ]
- Move all the selected emails to a certain folder

**Comment by The-Hidden-Hand** [comment]
@putulopi
Thanks for your suggestions.

Please let us know all the improvements you would like to see, and we'll do our best to accomplish them.

**Comment by alexdwork2018** [comment]
https://github.com/CTemplar/android/commit/dd0e81a7822dfd2f7ba07c4ac46de24949bc1120
Created view elements for the multiple messages selection feature. Each message item now includes a checkbox for selection and foreground overlay on a long click. The message display adapter is extended to support selected messages functionality. Also made code improvements in the main message adapter to optimize and new features integration.

https://github.com/CTemplar/android/commit/33af865827c818bc2adba096e28c4f9b2f34472e
Implemented logic for keep selected messages in the adapter. Adapter can return the list of selected messages and current selection state. Created options menu for selection state.

https://github.com/CTemplar/android/commit/df55ebde98c9d553408df5933f3d93d8c92a31b8
On the messages list screen added state listener which updates the toolbar menu when the user switches to the message selection mode. Created function that replaces the open drawer menu button with the cancel messages selection mode button. The left drawer menu will be blocked until selection mode is active to prevent accidental actions.

https://github.com/CTemplar/android/commit/7017656505c1ad02b8baffe134dd257058ebe17f
Implemented open and close functions for the selection menu. Worked on improving selection logic.

https://github.com/CTemplar/android/commit/99e75edb9b59d5ac9535910703c13222675e7efc
Implemented functionality for 'delete' and 'mark as read' toolbar actions with selected messages in the list. Applied the unified color scheme for message items in the selection messages mode. Made automatic selection message item on click the item checkbox and changing checkbox state when clicking on the message item itself. Changed to default theme accent color for all message screen snackbar's and other small improvements.

https://github.com/CTemplar/android/commit/88897a63cb4e8e9a95c03325f504621ef13eefca
Implemented delete multiple selected message items logic with 'undo' functionality. Created new functions for processing message items in the adapter and DB. Dependent inbox screen code and requests updated.

https://github.com/CTemplar/android/commit/804a848f7bdef4f8dfe2385f60374f2daaa586b1
Fragment for move messages feature was reworked. Now it supports movement of a group of messages. The screen fragment code itself improved, added support for binding. Fragment layout views optimized for better performance and readability. The logic of the main messages screen movement functions updated in accordance with the above changes, added error handlers.

https://github.com/CTemplar/android/commit/d0cca75104bf2e2246414364180b1076702f647b
https://github.com/CTemplar/android/commit/496869f600809c695c7c59289311fdb9171ad41a
All changes on the ticket were applied to the F-Droid branch and checked. Made a few smoke tests with the new functionality. Fixed bug on remaining selection after exiting the selection mode. Added processing to disable loading of messages until full exit from the selection mode to avoid data mixing.

https://github.com/CTemplar/android/commit/51d4430458d74a0417d42c371e971bf53e976425
Implementation animation algorithm for selection mode. Fixed loading errors that found during smoke tests.

https://github.com/CTemplar/android/commit/3d2a10c6f1661145fc21fdc848c050fd696f9321
Implemented of selectable animation in the F-Droid version. Done few smoke tests.

**Comment by The-Hidden-Hand** [comment]
Very good Alex. The following improvements shall be released with the next version.
