### ISSUE TITLE
Automatically Add an 'Re:' infront of the subject when you're replying to someone

### ISSUE THREAD

**Issue by Tuwikan** [CTemplar/android#334]
So that person knew it was a reply from the first message.

**Comment by The-Hidden-Hand** [comment]
@nivritgupta 
Are we doing this on iOS?

**Comment by alexdwork2018** [comment]
Hello @Tuweikan . This and the other small fixes regarding the answer functionality are already done and will be available in the next version of the app. Thanks for your reporting!

**Comment by The-Hidden-Hand** [comment]
@alexdwork2018 
I think you've also added `Fwd` when forwarding, let me know if not.
