### ISSUE TITLE
Prevent third-party keyboards usage

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/android#335]
### Expected behavior

Verify that the app prevents usage of custom third-party keyboards whenever sensitive data is entered.

- [ ] Point 2.5 https://github.com/OWASP/owasp-masvs/blob/master/Document/0x07-V2-Data_Storage_and_Privacy_requirements.md 
- [ ] Point 6.11 https://github.com/OWASP/owasp-masvs/blob/master/Document/0x11-V6-Interaction_with_the_environment.md

**Comment by The-Hidden-Hand** [comment]
@nivritgupta
Doesn't apply to iOS?

**Comment by The-Hidden-Hand** [comment]
@nivritgupta

**Comment by nivritgupta** [comment]
@The-Hidden-Hand these days many third party support ios devices as well but I disable any third party to replace the default keyboard.

**Comment by The-Hidden-Hand** [comment]
@nivritgupta 
Ok, I was asking because you moved this to Review so I was lost.

**Comment by xxxcrow** [comment]
So.. i will need to make my florisboard keyboard a system app? 🥲

**Comment by The-Hidden-Hand** [comment]
:thinking:

**Comment by The-Hidden-Hand** [comment]
It's for... security? haha
We can reconsider, but best practices suggest blocking them.

**Comment by xxxcrow** [comment]
@The-Hidden-Hand yeah, blocking third party keyboards, but probably from google play where many apps are malicious either potentially or just
And when a keyboard becomes third party? If for example i take the same floris and build aosp with it inside 😂 
and at the end what is not a third party keyboard? Google keyboard? Swift keyboard? Aosp? First two you can download as third party apps 😂

**Comment by The-Hidden-Hand** [comment]
Alright, let's not make that our responsibility for now and let users decide on their usage.
