### ISSUE TITLE
Hide the sensitive data when app is not in the foreground

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/android#336]
### Expected behavior

Point 2.9 https://github.com/OWASP/owasp-masvs/blob/master/Document/0x07-V2-Data_Storage_and_Privacy_requirements.md 

- [ ] Include a local setting for blurring the app preview when it's in the background.

**Comment by The-Hidden-Hand** [comment]
This is additional to the PIN protection and can be enabled independently.

**Comment by The-Hidden-Hand** [comment]
@nivritgupta 
Did you work on this one or did I move it by mistake? It was at the end of the list.

**Comment by The-Hidden-Hand** [comment]
@nivritgupta

**Comment by nivritgupta** [comment]
@The-Hidden-Hand  this task is done, since a few weeks ago
