### ISSUE TITLE
can't send email when encrypted

### ISSUE THREAD

**Issue by hakaishi** [CTemplar/android#342]
With the current version on f-droid sending normal emails works, but not for encrypted mails.
In the notification bar it's saying "sending email" without ever completing.

**Comment by The-Hidden-Hand** [comment]
Dear @hakaishi ,

Thanks for your report. We are aware of this issue caused after we upgraded the mentioned feature on the web. The Android app is getting updated and will support the latest version within one or two weeks.

Please, let us know if you have any other issues or suggestions for our services at any time.

**Comment by alexdwork2018** [comment]
Hello @hakaishi . The feature has been completely redesigned in accordance with the Web Client and is already available in the Google Play. The update is also ready for the F-Droid version, but will be available later due to the peculiarities of their automatic assembly system from the source-code.
