### ISSUE TITLE
Inbox: Filters UI and impl???

### ISSUE THREAD

**Issue by The-Hidden-Hand** [CTemplar/android#347]
https://app.zeplin.io/project/5b40afb49512418956aa99c2/screen/5b40b1466332f5040b3b09ef

https://app.zeplin.io/project/5b40afb49512418956aa99c2/screen/5b40b178c7b46c2456ddac6d

**Comment by alexdwork2018** [comment]
Hello @The-Hidden-Hand . Yes, the filter functionality is implemented in the Android app in accordance with the images in the above links.

**Comment by The-Hidden-Hand** [comment]
@alexdwork2018 
Ok, this was from Jira.
