### ISSUE TITLE
Unrecognized Email Address

### ISSUE THREAD

**Issue by SecretestSquirrel** [CTemplar/android#357]
### Environment 

F-droid app v1.4.6, on both Samsung S8+ running Android 9 and Pixel 4a running CalyxOS Android 11.

### Steps to reproduce

1. Enter email@protonmail.ch recipient address
2. Get error saying to "Enter Valid Email Address"
![](https://user-images.githubusercontent.com/74485231/115818419-b9271680-a3ca-11eb-8303-00382348f258.jpg)

### Expected behavior

Send email. It should be noted I switched to the web client and was able to send the message without issue.

### Actual behavior

Received error shown in picture above, unable to send message.

**Comment by alexdwork2018** [comment]
Hello @SecretestSquirrel . I tried repeating the error with the recipient address you provided, but no such error occurs. Perhaps there are characters in the email you entered that cannot pass the filter, then please let us know the full address of the recipient caused this problem. Also, you can try to repeat this bug in the latest version of the app.

**Comment by SecretestSquirrel** [comment]
>  Also, you can try to repeat this bug in the latest version of the app.

App version 1.4.7 I cannot replicate the issue. There was only alphabetical characters in the address when it was giving me an error before fwiw, but whatever the cause it seems to be resolved on my end by v1.4.7. Thanks!
