### ISSUE TITLE
Connection error when attempting to empty the Drafts folder

### ISSUE THREAD

**Issue by ghost** [CTemplar/android#388]
### Your environment

Ctemplar F-Droid app version 1.4.9. OS - Android 11. Device - Pixel 4a.

### Steps to reproduce

1. Open the Ctemplar app.
2. Navigate to "Drafts" folder.
3. Tap on menu button.
4. Tap on "Empty folder" option.
5. Confirm that user would like to empty folder.

![screenshot1](https://user-images.githubusercontent.com/86431633/123326285-e9378680-d4ed-11eb-8404-c16d55b589f9.png)
![screenshot2](https://user-images.githubusercontent.com/86431633/123326297-ec327700-d4ed-11eb-81ec-b165076e56b9.png)
![screenshot3](https://user-images.githubusercontent.com/86431633/123326307-ef2d6780-d4ed-11eb-847a-e4020c3e7be7.png)

### Expected behavior

All draft messages in the "Drafts" folder are actually emptied to the "Trash."

### Actual behavior

An error message results which reads "connection error." User is not experiencing any issues with home internet or LTE connection on mobile device. User has already attempted clearing cache, clearing data, uninstalling the app and reinstalling. The  error is encountered in the "Drafts" folder every time emptying it is attempted.

**Comment by alexdwork2018** [comment]
Hi @ghost . The fix is already completed and will be available in the next version of the app. Thanks for reporting the issue!
