### ISSUE TITLE
Can't delete email using the bin icon

### ISSUE THREAD

**Issue by reg3xp** [CTemplar/android#437]
### Your environment

OS: Android  11
Version: 1.5.6 F-Droid

### Steps to reproduce

1. Open an email
2. Use the delete button (bin icon)
3. See the pop up saying 1 message removed
4. The email remains in the inbox (nothing happens)
### Expected behavior
Email should be moved to Trash

### Actual behavior
Nothing happens

**Comment by The-Hidden-Hand** [comment]
Solved! Thanks for reporting.
