### ISSUE TITLE
Bug with touch function

### ISSUE THREAD

**Issue by TeaqariaWTF** [CTemplar/android#441]
My device Poco X3 
Android version 12
my android 12 device also sometimes does not detect touches and messages are not deleted

Video Link : https://gofile.io/d/fQTMVb

**Comment by alexdwork2018** [comment]
@TeaqariaWTF Hi. Sorry, your video link doesn't work. Can you please update it?

**Comment by alexdwork2018** [comment]
@The-Hidden-Hand The issue may have been fixed by a recent swipe handling improvement - https://github.com/CTemplar/android/pull/476

**Comment by The-Hidden-Hand** [comment]
Thanks

**Comment by TeaqariaWTF** [comment]
Problem solved with new update
