### ISSUE TITLE
Onion api domain Internal Server Error

### ISSUE THREAD

**Issue by BayLee4** [CTemplar/android#442]
The onion URL http://api.ctemplarpizuduxk3fkwrieizstx33kg5chlvrh37nz73pv5smsvl6ad.onion/ is down: 

```
500 Internal Server Error

Exception inside application.
Daphne
```

The clearnet api domain is working fine.

**Comment by BayLee4** [comment]
Seems resolved now.

**Comment by The-Hidden-Hand** [comment]
We have made some improvements in the threading of the underlying server to improve the API speed response and it has been restarted a few times during the tests.

Thanks for letting us know @BayLee4

**Comment by BayLee4** [comment]
@The-Hidden-Hand It's happening again today (I guess for the same reasons, so I'll leave this issue closed as it should be resolved soon).
