### ISSUE TITLE
Prevent Android App Manager taking screenshots

### ISSUE THREAD

**Issue by raven9nine** [CTemplar/android#456]
Most security related apps implement a method to prevent Android from making screenshots of apps thst display sensetive data like private email or contacts

**Comment by The-Hidden-Hand** [comment]
Dear customer,

Screenshots cannot be taken if the app preview is disabled. Thus, they will not work if the appropriate setting is enabled (github.com/CTemplar/android/issues/336) or a pin lock is set.

Please let us know if the option is not clear or you have further suggestions.

**Comment by raven9nine** [comment]
Please explain where is the 'disable app preview' setting.

**Comment by The-Hidden-Hand** [comment]
@raven9nine I've just confirmed this feature has been developed recently and it will not be public until the next app version is released within the next coming days (probably next week as it will include other improvements).
