### ISSUE TITLE
Can't login after password change

### ISSUE THREAD

**Issue by xxxcrow** [CTemplar/android#474]
### Your environment

1.5.9
Android 10

### Steps to reproduce

1. Login to the ctemplar app
2. Change your password (it will log you out)
3. Type the new credentials
4. Get a sign about wrong credentials

### Expected behavior

Just logging in, as it does on the web client

### Actual behavior

It doesn't let you to log in, and says my login/pass is wrong

**Comment by xxxcrow** [comment]
I changed my password and it started to work again! 
Worth mentioning, sometimes it was letting me go to the otp screen, but was logging me out after the otp

**Comment by The-Hidden-Hand** [comment]
@alexdwork2018 FYI.

I'm glad to know it was working. I'm closing the ticket for now and will wait for more input from you or Alex. Thanks.
